using RimWorld.Planet;
using Verse;

namespace MSSFP.Tunnels.MapComponents;

/// <summary>
/// Stores the originating TunnelCaravan's travel state on the temporary encounter map
/// generated by any member of the tunnel-caravan incident family
/// (IncidentWorker_TunnelCaravanSomethingHappened subclasses,
/// IncidentWorker_TunnelCaravanInsectAttack, IncidentWorker_TunnelCaravanFactionAmbush).
///
/// The caravan is destroyed by <see cref="CaravanEnterMapUtility.Enter"/> before the
/// encounter starts, so we capture its data here — via the static
/// <see cref="TunnelEncounterSetup.PendingCaravan"/> relay — at map-construction time.
/// After the encounter, a reform patch (commit 4) reads this component to re-create a
/// TunnelCaravan instead of a plain Caravan.
/// </summary>
public class MapComponent_TunnelCaravanState : MapComponent
{
    public PlanetTile origin;
    public PlanetTile destination;
    public Building_Tunnel tunnel;
    public int travelStartsAtTick;
    public int travelEndsAtTick;
    public bool hasData;

    public MapComponent_TunnelCaravanState(Map map) : base(map)
    {
        TunnelCaravan pending = TunnelEncounterSetup.PendingCaravan;
        if (pending == null) return;

        // Guard against a race where some unrelated map is constructed while a tunnel
        // encounter is pending: only the map generated for the active encounter's tile
        // (the same identity check TunnelEncounterPatch and TunnelCaravanReformMass_Patch
        // use) may consume the relay.
        if (!TunnelEncounterSetup.HasActiveEncounter || map.Tile != TunnelEncounterSetup.ActiveEncounterTile)
            return;

        origin = pending.origin;
        destination = pending.destination;
        tunnel = pending.tunnel;
        travelStartsAtTick = pending.travelStartsAtTick;
        travelEndsAtTick = pending.travelEndsAtTick;
        hasData = true;

        TunnelEncounterSetup.PendingCaravan = null;
    }

    public override void ExposeData()
    {
        base.ExposeData();
        Scribe_References.Look(ref tunnel, "tunnel");
        Scribe_Values.Look(ref origin, "origin");
        Scribe_Values.Look(ref destination, "destination");
        Scribe_Values.Look(ref travelStartsAtTick, "travelStartsAtTick", -1);
        Scribe_Values.Look(ref travelEndsAtTick, "travelEndsAtTick", -1);
        Scribe_Values.Look(ref hasData, "hasData");
    }
}

/// <summary>
/// Transient static relay used to pass the TunnelCaravan's state into
/// <see cref="MapComponent_TunnelCaravanState"/> at map-construction time,
/// and to carry that state through to the post-fight reform without depending
/// on <c>pawn.MapHeld</c> being non-null or a specific ExitMapAndCreateCaravan overload.
///
/// Set by all tunnel-caravan incident workers via
/// <see cref="MSSFP.Tunnels.Incidents.IncidentWorker_TunnelCaravanSomethingHappened.CaptureEncounterSetup"/>
/// before base executes.  Cleared either by the postfix that replaces the reformed
/// caravan, or by the map-removal patch if the player never reforms (both commit 4).
/// </summary>
public static class TunnelEncounterSetup
{
    // Used by MapComponent_TunnelCaravanState constructor
    public static TunnelCaravan PendingCaravan;

    // Authoritative state used by the (commit 4) reform patch.
    // Survives the caravan being destroyed by CaravanEnterMapUtility.Enter.
    public static bool HasActiveEncounter;
    public static PlanetTile ActiveEncounterTile; // tile where the fight spawned
    public static PlanetTile ActiveOrigin;
    public static PlanetTile ActiveDestination;
    public static Building_Tunnel ActiveTunnel;
    public static int ActiveTravelStartsAtTick;
    public static int ActiveTravelEndsAtTick;
}
